server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
      - id: produceModule
        uri: http://localhost:8081/
        predicates:
        - Path=/produce/**
      - id: consumerModule
        uri: http://localhost:8082/
        predicates:
        - Path=/consumer/**
